/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc2022

import aoc2022.*
import aoc2022.utils.InputReader

fun day01Run() {
    val day01 = Day01()
    val caloriesList = day01.readFileLineByLine("src/day01.txt")
    println(day01.getMaxCalories(caloriesList))
    println(day01.getTop3CalorieCount(caloriesList))
}

fun day02Run() {
    val day02 = Day02()
    val input = InputReader.readFileFromResource("day02.txt")
    println(day02.getTotalScore(input))
    println(day02.getTotalScoreCorrectly(input))
}

fun day03Run() {
    val day03 = Day03()
    val input = InputReader.readFileFromResource("day03.txt")
    println(day03.getPrioritySum(input))
}

fun main() {
    day01Run()
    println("------------------")
    day02Run()
    println("------------------")
    day03Run()
}
