/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc2022

import aoc2022.Day01

fun day01Run() {
    val day01 = Day01()
    val caloriesList = day01.readFileLineByLine("src/day01.txt")
    println(day01.getMaxCalories(caloriesList))
    println(day01.getTop3CalorieCount(caloriesList))
}

fun main() {
    day01Run()
}
