/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc2022

import aoc2022.*
import aoc2022.utils.InputReader

fun day01Run() {
    val day01 = Day01()
    val caloriesList = day01.readFileLineByLine("src/day01.txt")
    println(day01.getMaxCalories(caloriesList))
    println(day01.getTop3CalorieCount(caloriesList))
}

fun day02Run() {
    val day02 = Day02()
    val input = InputReader.readFileFromResource("day02.txt")
    println(day02.getTotalScore(input))
    println(day02.getTotalScoreCorrectly(input))
}

fun day03Run() {
    val day03 = Day03()
    val input = InputReader.readFileFromResource("day03.txt")
    println(day03.getPrioritySum(input))
    println(day03.getBadgeSum(input))
}

fun day04Run() {
    val day04 = Day04()
    val input = InputReader.readFileFromResource("day04.txt")
    println(day04.getOverlappingCount(input))
    println(day04.getIntersectinCount(input))
}

fun day05Run() {
    val day05 = Day05()
    val input = InputReader.readFileFromResource("day05.txt")
    println(day05.getResultFromMoves(input))
    println(day05.getResultFromMultiMoves(input))
}

fun day06Run() {
    val day06 = Day06()
    val input = InputReader.readFileFromResource("day06.txt")
    println(day06.part01(input))
    println(day06.part02(input))
}

fun day07Run() {
    val day07 = Day07()
    val input = InputReader.readFileFromResource("day07.txt")
    println(day07.part01(input))
}

fun day08Run() {
    val day08 = Day08()
    val input = InputReader.readFileFromResource("day08.txt")
    println(day08.part01(input))
}

fun day10Run() {
    val day10 = Day10()
    val input = InputReader.readFileFromResource("day10.txt")
    println(day10.part01(input))
}
fun main() {
    day01Run()
    println("------------------")
    day02Run()
    println("------------------")
    day03Run()
    println("------------------")
    day04Run()
    println("------------------")
    day05Run()
    println("------------------")
    day06Run()
    println("------------------")
    day07Run()
    println("------------------")
    day08Run()
    println("------------------")
    day10Run()
}
